fix ci for aslp_server. however...
the parent aslp repository seems to be aware of the child project
when executing `dune install`.
this leads to problems like

    $ dune install
    Error: The following <package>.install are missing:
    - _build/default/aslp_server/aslp_server.install
    Hint: try running 'dune build [-p <pkg>] @install'

running the suggested `dune build -p aslp_server @install`
will fail because asli is not installed yet.

so you have to

    dune build
    dune install -p asli
    dune build -p aslp_server @install
    dune install -p aslp_server

which is a bit uncomfortable